# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f29d8dba19b38e9f0528ed0d0a62e75159cc9e9715720f0e0d740cb8ca1c97466ba33bd5fe7cda0dab16ad17b95e8aec8af6bbd38f9512f72be4a86b0191ec0

test:
  secret_key_base: 6ed8ac3417bee7ecfc277e18b9edb422ebc16f9e7c0e3fb620ca180155bfb18a381fd5c844c389e8e01bd12e383355c2bbc909a6464aa001e587eb84dabb5609

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
